FROM python:3.10.1-slim

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY .streamlit/config.toml ~/.streamlit/config.toml

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

#ENTRYPOINT ["streamlit", "run", "Home.py"]

CMD streamlit run Home.py --theme.base="dark"